### ISSUE TITLE
Encrypted file request results in LogicException

### ISSUE THREAD

**Issue by TravisCarden** [d8-contrib-modules/file_encrypt#19]
@dawehner: I'm encountering the following error trying to download a file encrypted with `file_encrypt`:

> AH01071: Got error 'PHP message: Uncaught PHP Exception LogicException: "The controller must return a response (encrypt given)." at /var/www/vendor/symfony/http-kernel/HttpKernel.php line 162 '

The download URI is `/encrypt/files/my_kms/subdir/file.pdf`, which is what `$request->getRequestUri()` returns inside `\Drupal\system\FileDownloadController::download()`.

I'm using `real_aes` for encryption. I'm also using `workbench_moderation` and doing multilingual with path-based language negotiation (e.g., `/fr/node/1`).

**Comment by TravisCarden** [comment]
After integrating new development and reinstalling my site, I can no longer reproduce this issue. Closing until and unless it resurfaces.

**Comment by dawehner** [comment]
Thank you for keeping us up to date!

I'm happy to try to reproduce when you think there is a realistic opportunity for it to exists
