### ISSUE TITLE
Encrypted files don't download properly due to incorrect Content-Length header value

### ISSUE THREAD

**Issue by TravisCarden** [d8-contrib-modules/file_encrypt#20]
I have successfully implemented file encryption (using `real_aes`) and have it working with most cases I have tested, but I cannot get it to work with PDF files. It saves and appears to encrypt the files, but when I attempt to download them the request always whitescreens. It doesn't cause any PHP errors or warnings, and it doesn't save any messages in the log. Following the request logic with Xdebug, I see that it gets all the way to sending a `BinaryFileResponse` with a `file` member that looks correct and terminating the kernel cycle. Firefox Developer Tools indicate that the browser is receiving an HTTP 200 response of HTML type a little smaller than the actual file (289K, whereas the original PDF is 292K).

I'm really not sure where to go from here. Has `file_encrypt` been tested with PDF files, specifically? Does anyone have any recommendations how I might proceed from here to isolate the problem? cc @dawehner

**Comment by TravisCarden** [comment]
I no longer believe the problem to be in `file_encrypt`. I created a couple of test encryption profiles--one that uses the ROT13 transformation and another that doesn't actually do anything--and the same file fields worked with PDFs using either of those profiles. Thus I now suspect the problem to be in `real_aes`. Closing this issue. Thanks!

**Comment by colans** [comment]
@TravisCarden : When there is one, would you kindly add a link here to that issue?

**Comment by dawehner** [comment]
Interesting to know!

**Comment by TravisCarden** [comment]
Here it is, @colans: [Problems decrypting files [#2765745]](https://www.drupal.org/node/2765745)!

**Comment by TravisCarden** [comment]
I found the problem! It's not in any of the Drupal modules at all. It's in the Symfony `http-foundation` component: https://github.com/symfony/symfony/issues/19738. The encrypt suite works perfectly, but it gets invoked and changes the file contents after the HTTP response object has already sent the `Content-Length` header, causing a mismatch with the data actually received by the browser, which therefore chokes on it. The reason my earlier test with an ROT13 encryption method worked is because that cipher doesn't actually change the file size. (What a red herring!)

@nerdstein: I plan to solve this for my project by patching Symfony via Composer per the issue linked above. Of course that doesn't solve it for anyone else. Reopening for discussion of a solution for the community.

**Comment by nerdstein** [comment]
@TravisCarden can you update the drupal.org issue as well?

I'm wondering if we can somehow tap into this and configure it.

**Comment by TravisCarden** [comment]
@nerdstein You mean the issue filed against `real_aes`? That was a complete red herring. Not only was the problem not there, it's not solvable there. It IS solvable here in `file_encrypt`. And that's what I intend to do, actually--solve it here--after taking just a brief look at what it would take to patch `symfony/http-foundation` two layers deep via Composer! I'm going to work on modifying the `file_encrypt.file_download` service to instantiate a new `EncryptBinaryFileResponse` that subclasses `BinaryFileResponse` and overrides that one bit of behavior we care about. It shouldn't be too big a deal. I plan to have a PR soon.

**Comment by nerdstein** [comment]
And this is why you rock

## Adam Bergstein 

Email sent via mobile device, please overlook mistakes

**Comment by TravisCarden** [comment]
Here you go, @nerdstein! ^^
