### ISSUE TITLE
Moving encrypted files with rename() leaves them unencrypted on disk

### ISSUE THREAD

**Issue by TravisCarden** [d8-contrib-modules/file_encrypt#22]
PHP does not necessarily call the `stream_close()` method on stream wrappers every time it calls `stream_open()`. For example, when copying a file (`copy()`) it calls both, but when moving a file (`rename()`) it does not. The result is that renaming a file using `EncryptStreamWrapper` decrypts the file but does not re-encrypt it, leaving it unencrypted on disk. And when core issue [file_unmanaged_move() should issue rename() where possible instead of copy() & unlink() [#1377740]](https://www.drupal.org/node/1377740) landed (8.1.4), this problem became acute. I discovered this by way of the [dropzonejs](https://www.drupal.org/project/dropzonejs) entity browser widget, which uses `file_unmanaged_move()` to save new uploads. I played around with moving the encryption to a different method (i.e., `stream_write()`), but without success. It has been suggested to me that we shouldn't be using stream wrappers to solve this problem in the first place--that encryption is a job for PHP [stream filters](https://secure.php.net/manual/en/stream.filters.php) instead. (Perhaps switching to filters would help with #5, too.) @dawehner

**Comment by nerdstein** [comment]
Please follow this: https://github.com/defuse/php-encryption/issues/283

**Comment by dawehner** [comment]
This issue, given its security implications, is certainly critical.

I'll try to experiment more with stream filters, which also would give us more experience to maybe solve the streaming aspect of things

**Comment by TravisCarden** [comment]
Using stream filters, per https://github.com/d8-contrib-modules/file_encrypt/pull/23, seems to fix this issue.

**Comment by TravisCarden** [comment]
Moved to https://www.drupal.org/node/2802455.
