### ISSUE TITLE
Investigate using encrypt:// in a file field

### ISSUE THREAD

**Issue by dawehner** [d8-contrib-modules/file_encrypt#6]
> Use case:
> 
> Given I'm a site builder
> When I select `encrypt://` in the file field settings
>   and I upload a file
> Then file should be encrypted on disk

Let's investigate whether selecting the encrypt stream is already possible and works properly.

Also let's ensure to make it clear in the README how users can configure file fields for that.

**Comment by dawehner** [comment]
#9 attempts to solve this

**Comment by nerdstein** [comment]
Closing. I'm comfortable with the progress here and will open new issues if needed
